Basket
tUnknownLegend/TP-QA-HW-1 pull request #1
Opened 2023-02-19 10:08 UTC by Liza1040

2023-02-19 21:22 UTC, tUnknownLegend requested changes
В целом все классно, но несколько моментов надо обсудить. Еще стоит сделать проверку на обновление страницы - как минимум дата и время доставки не сохранятся

2023-02-19 21:22 UTC, tUnknownLegend commented on Base.md
> +    - *Маленький баг.* кликабелен не только сам чекбокс, но и вся строка, в которой он находится
Не уверен, что это баг, скорее фича :)

2023-02-19 21:22 UTC, tUnknownLegend commented on Base.md
> +      <img src="/images/product_name_line.png" alt="Строка с названием товара">
На счет скринов - давай делать скрин полной страницы (или части, но так чтобы было понятно что на скрине) и выделять элемент, в котором баг. Мы с вами можем понять, что на текущих скринах - человеку незнакомому с проектом будет затруднительно это сделать

2023-02-19 21:22 UTC, tUnknownLegend commented on Base.md
> +    - *Маленький баг.* кликабельно не только название, но и вся строка, в которой оно находится
Давайте решим как будем категоризовать баги. Можно как в лекции - на английском, можно на русском, раз уж начали так. Предлагаю баги с высокой severity дополнительно выделять дополнительно как-то. Можно незначительные баги кeрсивом, обычные жирным, критичные жирным и курсивом. Соответвенно названия либо minor - major - critical, либо как-то на русском это представить адекватно, на как major норм перевести не приходит в голову :)

2023-02-19 21:22 UTC, tUnknownLegend commented on Base.md
> +#### Блок "Корзина"
Можно добавить скрин с выделение этого блока. Может и лишнее, как думаете?

2023-02-23 17:17 UTC, thelvv commented on Base.md
> +    - *Маленький баг.* кликабельно не только название, но и вся строка, в которой оно находится
Можно писать незначительный - значительный - критический соответственно. Насчет выделения - я бы помечал все баги курсивом, обычные +подчеркиванием и критичные +подчеркиванием и жирным шрифтом.

2023-02-23 17:21 UTC, thelvv commented on Base.md
> +#### Блок "Корзина"
Скрин всей страницы или скрин всего посередине, что не хедер и не футер? Идея хорошая, общий скрин лишним не будет

2023-02-27 14:57 UTC, tUnknownLegend commented on Base.md
> +#### Блок "Корзина"
Делаем общий скрин на каждый блок и выделяем сам блок. Для багов делаем скрин блока и выделяем на нем баг

2023-03-02 11:28 UTC, Liza1040 commented on Base.md
> +    - *Маленький баг.* кликабелен не только сам чекбокс, но и вся строка, в которой он находится
Красивый ход) Я бы оставила, потому как это не типичное поведение. Я совершенно случайно его обнаружила - просто кликнула на пустое место, а оказалось чекбокс сработал

2023-03-02 14:42 UTC, tUnknownLegend approved these changes

2023-03-04 21:15 UTC, merged