Исправление комментариев
tUnknownLegend/TP-QA-HW-1 pull request #10
Opened 2023-03-12 23:41 UTC by tUnknownLegend

- Добвлены ссылки
- Инструкция по проверке какие компоненты перерендриваются
- Другие исправления

2023-03-12 23:56 UTC, thelvv commented on Base.md
> +- [Открыть](https://developer.chrome.com/docs/devtools/rendering/) вкладку рендра
рендера*

2023-03-12 23:56 UTC, thelvv commented on Base.md
> + - При клике на фото открывается страница [товара](https://github.com/tUnknownLegend/TP-QA-HW-1/edit/Base/Base.md#c%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B0)
в некоторых местах (например, 159 строка) ты оставляешь ссылку на соответствующую страницу на сайте, а в других - на пункт, посвященный этой странице. думаю, надо выбрать что-то одно

2023-03-13 01:01 UTC, tUnknownLegend commented on Base.md
> + - При клике на фото открывается страница [товара](https://github.com/tUnknownLegend/TP-QA-HW-1/edit/Base/Base.md#c%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%B0)
Исиправил. Теперь все ссылки ведут на сайт. Ссылки на markdown, только в случае, если идет речь про аналогичный блок

2023-03-13 02:19 UTC, EuphoriaAbsorber requested changes

2023-03-13 02:19 UTC, EuphoriaAbsorber commented on Base.md
> +# Как проверить перенрдривается ли компонент
опечатка в заголовке

2023-03-13 02:19 UTC, EuphoriaAbsorber commented on Base.md
>   - Категория соответствует категории данного товара
к этой строке у ментора был комментарий

2023-03-13 08:20 UTC, Liza1040 approved these changes

2023-03-13 08:50 UTC, thelvv approved these changes

2023-03-14 11:23 UTC, EuphoriaAbsorber approved these changes

2023-03-14 11:33 UTC, merged