Update Base.md
tUnknownLegend/TP-QA-HW-1 pull request #11
Opened 2023-03-13 02:13 UTC by EuphoriaAbsorber

2023-03-13 08:53 UTC, thelvv approved these changes

2023-03-13 11:13 UTC, Liza1040 approved these changes

2023-03-13 17:07 UTC, tUnknownLegend requested changes

2023-03-13 17:07 UTC, tUnknownLegend commented on Base.md
> +- При клике на фразу "по цене" и при отображении иконки большим основанием вниз происходит сортировка товаров по возрастанию цены.
на кнопку с текстом?

2023-03-13 17:07 UTC, tUnknownLegend commented on Base.md
> +- На странице категории "Телефоны" все товары относятся к категории "Телефоны".
Как это проверить? У себя такое расписвал в комменте, который ты оставлял, можно будет сослаться или вынести в общие паттерны

2023-03-14 11:58 UTC, tUnknownLegend approved these changes

2023-03-14 11:58 UTC, merged