Profile
tUnknownLegend/TP-QA-HW-1 pull request #3
Opened 2023-03-01 15:11 UTC by thelvv

2023-03-01 19:37 UTC, tUnknownLegend requested changes

2023-03-01 19:37 UTC, tUnknownLegend commented on Base.md
> +    - __Уязвимость:__ отсутствует валидация полей
Это все таки не уязвимость, потому что xss по факту нет, можешь потетстить. Здесь по идеи должна быть интеграция карт, поэтому нет валидации. Можно просто как-то инчае назвать, но в целом в плане безопастности проблем нет, в остальном челоаек сам должен чекать

2023-03-01 19:37 UTC, tUnknownLegend commented on Base.md
> +  - *Незначительный баг:* при добавлении аватарки она не обрезается под нужную форму, а остается в исходном соотношении сторон
Может мне фикс залить, а то как-то стыдно такое кидать?)

2023-03-01 20:40 UTC, thelvv commented on Base.md
> +    - __Уязвимость:__ отсутствует валидация полей
Ну да, согласен, это не совсем уязвимость, а скорее необходимость либо валидации, либо прикрученных предложений для дозаполнения формы

2023-03-01 20:53 UTC, tUnknownLegend approved these changes

2023-03-02 10:05 UTC, tUnknownLegend requested changes
Отмена по аппруву :( для багов надо указывать корректное поведение

2023-03-02 11:27 UTC, tUnknownLegend approved these changes

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - При наведении на фотографию пользователя при добавленной аватарке появляется блок кнопок изменения и удаления аватарки
Этот пункт абсолютно идентичен предыдущему

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - *Незначительный баг:* при клике на кнопку изменения аватарки и отмене выбора файла удаляется старая аватарка, при этом кнопок все еще две - для изменения и удаления аватарки. Лечится перезагрузко
По-моему баг тянет на значительный. Что думаешь?

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +    ![image](https://user-images.githubusercontent.com/59176894/222013284-802b1cf9-8dd3-4c27-afef-75f88a0f2927.png)
Нужен ли этот скрин, это же не баг. Я бы скрины вставляла только на баги и на основные блоки, которые тестишь

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - При клике по инпуту вокруг него появляется граница темного цвета, при клике вне инпута граница пропадает.
Про подсветку ты тут снова пишешь, а про кнопку отмены уже нет. Странновато, нужно либо это убрать, либо кнопку отмены добавить (но тогда в блоках с телефоном и паролем было бы хорошо добавить оба пункта)

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - При нажатии "Применить" в случае заполненных полного корректного заполнения формы применяются изменения. Поп-ап закрывается
С формулировкой беда, не особо понятно

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - При нажатии "Применить" в случае заполненных корректно инпута нового пароля и инпута для повтора пароля, но с неверно введенным текущим паролем справа сверху страницы появится сообщение о том, чт
Не баг ли это? Может в незначительный вынести? Странно, что сообщение там отображается

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +    ![image](https://user-images.githubusercontent.com/59176894/222164576-c3ea1699-7365-4f30-8e29-90a6d28dfc1f.png)
Незначительный баг, нелогичное расположение сообщения об ошибке

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +    ![image](https://user-images.githubusercontent.com/59176894/222171029-71d0594f-6114-49d8-a33a-8295759ebaa8.png)
Я бы все скрины с сообщениями об ошибке не вставляла, ты же итак в тексте описываешь, какое сообщение появляется. Мне кажется, достаточно одного скрина

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - При нажатии "Применить" в случае корректного заполнения полей номера карты, даты окончания действия карты и CVV-кода добавлявется новая платежная карта
опечатка в слове добавляется

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - __*Значительный баг:*__ при наведении курсора на карту - кнопка удаления карты появляется только поверх первой (левой); при нажатии на кнопку - удаляются все карты сразу __*(далее актуально и для
Чекнула этот баг на сайте, но у меня кнопка с удалением появляется еще и у 3 карты слева. И удаляется либо одна карта, либо две. Очень странный баг

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +    - *Незначительный баг:* отсутствует валидация/предложения для автозаполнение полей
Отсутствие валидации тянет на критический  баг. Мы ж не сможет доставлять товары, если адреса неверные, а это мешает бизнесу

2023-03-02 14:30 UTC, Liza1040 commented on Base.md
> +  - При наведении на карточку появляется блок кнопок с иконками редактирования и удаления карты.
Тут есть баг при добавлении всех 4 карт: кнопка с удалением и редактированием не появляется у последней(правой) карты. Если удалить вторую страва карту, удаляется и самая правая тоже. А если редактировать вторую справа карту, появится баг с двойным редактированием: в попапе появятся сразу две карты для редактирования. 
![Снимок экрана от 2023-03-02 17-13-41](https://user-images.githubusercontent.com/95960035/222457052-cc4001f0-8845-48dd-80e4-6667f90ae5d0.png)

2023-03-02 14:35 UTC, tUnknownLegend commented on Base.md
> +  - *Незначительный баг:* при клике на кнопку изменения аватарки и отмене выбора файла удаляется старая аватарка, при этом кнопок все еще две - для изменения и удаления аватарки. Лечится перезагрузко
Аватарака в маркетплейсе в целом не особо важна, главный функционал связан с корзиной, формление заказа, заполнения данных оплаты и доставки

2023-03-02 14:40 UTC, tUnknownLegend commented on Base.md
> +    - *Незначительный баг:* отсутствует валидация/предложения для автозаполнение полей
Баг - это когда некорректно поведение, а это продуктовая проблема. Должна быть интеграция карты и провреки существует ли такой адрес. В данном случае валидация вообще не закладывалась, т.е. это может быть как некорректность работы, но не баг

2023-03-02 14:42 UTC, thelvv commented on Base.md
> +  - *Незначительный баг:* при клике на кнопку изменения аватарки и отмене выбора файла удаляется старая аватарка, при этом кнопок все еще две - для изменения и удаления аватарки. Лечится перезагрузко
Она не приводит даже к незначительным искажением работы целевых функций типа выбора, оплаты и тд, так что мне кажется, все-таки незначительный

2023-03-02 14:45 UTC, thelvv commented on Base.md
> +    ![image](https://user-images.githubusercontent.com/59176894/222013284-802b1cf9-8dd3-4c27-afef-75f88a0f2927.png)
Для отображения функционала почему нет, лучше больше скринов, чем меньше

2023-03-02 14:46 UTC, thelvv commented on Base.md
> +  - При клике по инпуту вокруг него появляется граница темного цвета, при клике вне инпута граница пропадает.
Да, надо удалить, я пропустил

2023-03-02 14:51 UTC, thelvv commented on Base.md
> +  - При нажатии "Применить" в случае заполненных корректно инпута нового пароля и инпута для повтора пароля, но с неверно введенным текущим паролем справа сверху страницы появится сообщение о том, чт
в той области экрана обычно появляются сообщения, связанные с сетевыми ошибками, и это одно из них, а не валидация, так что по идее норм

2023-03-02 14:52 UTC, thelvv commented on Base.md
> +    ![image](https://user-images.githubusercontent.com/59176894/222164576-c3ea1699-7365-4f30-8e29-90a6d28dfc1f.png)
А тут да, с точки зрения единообразия дизайна результат валидации должен быть справа от инпута

2023-03-02 14:55 UTC, thelvv commented on Base.md
> +  - __*Значительный баг:*__ при наведении курсора на карту - кнопка удаления карты появляется только поверх первой (левой); при нажатии на кнопку - удаляются все карты сразу __*(далее актуально и для
Действительно странный, я проверил еще раз, и у меня все еще кнопка появляется только в левой карте и удаляет все разом

2023-03-02 16:52 UTC, Liza1040 commented on Base.md
> +  - При нажатии "Применить" в случае заполненных корректно инпута нового пароля и инпута для повтора пароля, но с неверно введенным текущим паролем справа сверху страницы появится сообщение о том, чт
Но это тоже ошибка пользовательского ввода, и логичнее ее отображать около поля. По крайней мере во всех реальных сервисах это так

2023-03-02 16:57 UTC, Liza1040 commented on Base.md
> +    - При нажатии на кнопку появляется поп-ап с формой для добавления новой банковской карты
Только тут добавление нового адреса, а не банковской карты

2023-03-02 17:02 UTC, Liza1040 commented on Base.md
> +    - *Незначительный баг:* отсутствует валидация/предложения для автозаполнение полей
Тогда может вообще это в баг не выделять?

2023-03-02 17:16 UTC, Liza1040 approved these changes

2023-03-02 18:04 UTC, thelvv commented on Base.md
> +    - *Незначительный баг:* отсутствует валидация/предложения для автозаполнение полей
Это можно назвать недоработкой скорее, напишу так

2023-03-04 21:09 UTC, merged